/*
Topik   : Sekolah
Anggota : Arpriansah Yonathan (1301194112)
          Balqis Sayyidahtul Atikah (1301193480)
          Igga Febrian Virgiani (1301194283)
          Manuel Benedict (1301194182)
 */
package GUI;

import Controller.ControllerAdmin;

public class guiAdmin extends javax.swing.JFrame {

    /**
     * Creates new form guiAdmin
     */
    public guiAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabelNama = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelTambahKelas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKelas = new javax.swing.JList<>();
        jLabelAdmin = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabelHapusKelas = new javax.swing.JLabel();
        jLabelInputKelas = new javax.swing.JLabel();
        tfNama1 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabelMapel = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabelInputNIS = new javax.swing.JLabel();
        tfKelas = new javax.swing.JTextField();
        jLabelInputNama = new javax.swing.JLabel();
        tfNIS = new javax.swing.JTextField();
        jCheckBoxPKn = new javax.swing.JCheckBox();
        jCheckBoxMM = new javax.swing.JCheckBox();
        jCheckBoxIPS = new javax.swing.JCheckBox();
        jCheckBoxIPA = new javax.swing.JCheckBox();
        jLabelKetHapus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabelNama.setText("Klik satu kelas yang akan dihapus");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTambahKelas.setText("TAMBAH KELAS");
        getContentPane().add(jLabelTambahKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 67, -1, -1));

        jListKelas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListKelas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 106, 196, 200));

        jLabelAdmin.setText("ADMIN SISTEM INFORMASI SEKOLAH");
        getContentPane().add(jLabelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 17, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabelHapusKelas.setText("HAPUS KELAS");
        getContentPane().add(jLabelHapusKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 67, -1, -1));

        jLabelInputKelas.setText("Kelas");
        getContentPane().add(jLabelInputKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, -1, -1));

        tfNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNama1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 187, 155, -1));

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 385, -1, -1));

        jLabelMapel.setText("Mata pelajaran");
        getContentPane().add(jLabelMapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 290, 196, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 342, -1, -1));

        jLabelInputNIS.setText("NIS");
        getContentPane().add(jLabelInputNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 227, -1, -1));

        tfKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKelasActionPerformed(evt);
            }
        });
        getContentPane().add(tfKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 124, 155, -1));

        jLabelInputNama.setText("Nama");
        getContentPane().add(jLabelInputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 164, -1, -1));

        tfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNISActionPerformed(evt);
            }
        });
        getContentPane().add(tfNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 250, 155, -1));

        jCheckBoxPKn.setText("PKn");
        jCheckBoxPKn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPKnActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxPKn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 315, -1, -1));

        jCheckBoxMM.setText("Matematika");
        jCheckBoxMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMMActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 342, -1, -1));

        jCheckBoxIPS.setText("IPS");
        jCheckBoxIPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIPSActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxIPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 342, -1, -1));

        jCheckBoxIPA.setText("IPA");
        jCheckBoxIPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIPAActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxIPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 315, -1, -1));

        jLabelKetHapus.setText("Klik kelas yang ingin dihapus");
        getContentPane().add(jLabelKetHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 319, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 56, 22, 379));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNama1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tfKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKelasActionPerformed

    private void tfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNISActionPerformed

    private void jCheckBoxPKnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPKnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPKnActionPerformed

    private void jCheckBoxMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMMActionPerformed

    private void jCheckBoxIPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIPSActionPerformed

    private void jCheckBoxIPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIPAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBoxIPA;
    private javax.swing.JCheckBox jCheckBoxIPS;
    private javax.swing.JCheckBox jCheckBoxMM;
    private javax.swing.JCheckBox jCheckBoxPKn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelHapusKelas;
    private javax.swing.JLabel jLabelInputKelas;
    private javax.swing.JLabel jLabelInputNIS;
    private javax.swing.JLabel jLabelInputNama;
    private javax.swing.JLabel jLabelKetHapus;
    private javax.swing.JLabel jLabelMapel;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTambahKelas;
    private javax.swing.JList<String> jListKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNama1;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ControllerAdmin aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void addMouseAdapter(ControllerAdmin aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
